import type { Trip, DayPlan, Activity } from "@/types"
import type { Language } from "@/stores/uiStore"

const ZH_LABELS = {
  toc: "目录", overview: "行程概览", basic: "基本信息",
  destination: "目的地", start: "开始日期", end: "结束日期", daysCol: "行程天数",
  actCount: "活动总数", totalBudget: "总预算", avgBudget: "日均预算",
  statusCol: "状态", itinerary: "详细行程", budgetSummary: "预算汇总",
  overallBudget: "总体预算", dailyDetail: "每日预算明细", dateCol: "日期", budgetCol: "预算",
  maxDay: "最高单日预算", minDay: "最低单日预算",
  dayBudget: "当日预算", actDetails: "活动详情",
  locLabel: "地点", addrLabel: "地址", typeLabel: "类型", costLabel: "费用",
  ratingLabel: "评分", bookLabel: "预订", notesLabel: "备注",
  footer: "由 Trip Agent 生成于",
  usage: "## 使用说明\n\n- 本文档为 Markdown 格式，可在支持 Markdown 的编辑器中打开\n- 导出 PDF 可使用浏览器打印功能（Ctrl/Cmd + P）",
  actType: (t: string) => ({ transportation:"交通", attraction:"景点", dining:"餐饮", accommodation:"住宿", shopping:"购物", other:"其他" }[t] ?? t),
  statusStr: (s: string) => ({ draft:"草稿", planning:"规划中", confirmed:"已确认", completed:"已完成", cancelled:"已取消" }[s] ?? s),
  dateLocale: "zh-CN",
  daysUnit: "天",
  dayTitle: (n: number, d: Date) => `### 第${n}天 - ${d.toLocaleDateString("zh-CN", { month:"long", day:"numeric", weekday:"short" })}`,
  tocDayRef: (n: number) => `第${n}天`,
}

const EN_LABELS: typeof ZH_LABELS = {
  toc: "Table of Contents", overview: "Trip Overview", basic: "Basic Info",
  destination: "Destination", start: "Start Date", end: "End Date", daysCol: "Days",
  actCount: "Activities", totalBudget: "Total Budget", avgBudget: "Daily Avg",
  statusCol: "Status", itinerary: "Itinerary Details", budgetSummary: "Budget Summary",
  overallBudget: "Overall Budget", dailyDetail: "Daily Budget Breakdown", dateCol: "Date", budgetCol: "Budget",
  maxDay: "Max Day Budget", minDay: "Min Day Budget",
  dayBudget: "Day budget", actDetails: "Activity Details",
  locLabel: "Location", addrLabel: "Address", typeLabel: "Type", costLabel: "Cost",
  ratingLabel: "Rating", bookLabel: "Book", notesLabel: "Notes",
  footer: "Generated by Trip Agent on",
  usage: "## Notes\n\n- This is a Markdown file, viewable in any Markdown editor\n- Export to PDF via browser print (Ctrl/Cmd + P)",
  actType: (t: string) => ({ transportation:"Transport", attraction:"Attraction", dining:"Dining", accommodation:"Stay", shopping:"Shopping", other:"Other" }[t] ?? t),
  statusStr: (s: string) => ({ draft:"Draft", planning:"Planning", confirmed:"Confirmed", completed:"Completed", cancelled:"Cancelled" }[s] ?? s),
  dateLocale: "en-US",
  daysUnit: " days",
  dayTitle: (n: number, d: Date) => `### Day ${n} — ${d.toLocaleDateString("en-US", { month:"long", day:"numeric", weekday:"short" })}`,
  tocDayRef: (n: number) => `Day ${n}`,
}

export class MarkdownExportService {
  static exportToMarkdown(trip: Trip, lang: Language = "zh"): void {
    const md = this.generateMarkdown(trip, lang)
    this.downloadFile(md, `${trip.name}.md`, "text/markdown")
  }

  static generateMarkdown(trip: Trip, lang: Language = "zh"): string {
    const L = lang === "en" ? EN_LABELS : ZH_LABELS
    let md = this.header(trip, L)
    md += this.toc(trip, L)
    md += this.overview(trip, L)
    md += this.itinerary(trip, L)
    md += this.budgetSummary(trip, L)
    md += this.footer(L)
    return md
  }

  private static header(trip: Trip, L: typeof ZH_LABELS) {
    return `# ${trip.name}\n\n> ${trip.destination.name}, ${trip.destination.country} · ${trip.duration.days}${L.daysUnit}\n\n`
  }

  private static toc(trip: Trip, L: typeof ZH_LABELS) {
    let s = `## ${L.toc}\n\n- [${L.overview}](#${L.overview.toLowerCase().replace(/\s+/g, "-")})\n`
    for (const d of trip.itinerary) s += `- [${L.tocDayRef(d.dayNumber)}](#day-${d.dayNumber})\n`
    s += `- [${L.budgetSummary}](#${L.budgetSummary.toLowerCase().replace(/\s+/g, "-")})\n\n`
    return s
  }

  private static overview(trip: Trip, L: typeof ZH_LABELS) {
    const total = trip.itinerary.reduce((s, d) => s + (d.estimatedBudget ?? 0), 0)
    const acts  = trip.itinerary.reduce((s, d) => s + d.activities.length, 0)
    const fmt   = (d: Date) => d.toLocaleDateString(L.dateLocale, { year:"numeric", month:"long", day:"numeric" })
    return `## ${L.overview}\n\n### ${L.basic}\n\n| | |\n|---|---|\n` +
      `| **${L.destination}** | ${trip.destination.name}, ${trip.destination.country} |\n` +
      `| **${L.start}** | ${fmt(trip.duration.startDate)} |\n` +
      `| **${L.end}** | ${fmt(trip.duration.endDate)} |\n` +
      `| **${L.daysCol}** | ${trip.duration.days}${L.daysUnit} |\n` +
      `| **${L.actCount}** | ${acts} |\n` +
      `| **${L.totalBudget}** | ¥${total.toFixed(0)} |\n` +
      `| **${L.avgBudget}** | ¥${(total / trip.duration.days).toFixed(0)} |\n` +
      `| **${L.statusCol}** | ${L.statusStr(trip.status)} |\n\n`
  }

  private static itinerary(trip: Trip, L: typeof ZH_LABELS) {
    let s = `---\n\n## ${L.itinerary}\n\n`
    for (const day of trip.itinerary) s += this.dayPlan(day, L)
    return s
  }

  private static dayPlan(day: DayPlan, L: typeof ZH_LABELS) {
    let s = `${L.dayTitle(day.dayNumber, day.date)}\n\n`
    s += `| ${L.daysCol === "Days" ? "Time" : "时间"} | ${L.destination === "Destination" ? "Activity" : "活动"} | ${L.locLabel} | ${L.typeLabel} | ${L.costLabel} |\n`
    s += `|---|---|---|---|---|\n`
    for (const a of day.activities) {
      s += `| ${a.time.start} – ${a.time.end} | ${a.name} | ${a.location.name} | ${L.actType(a.type)} | ${a.cost != null ? `¥${a.cost}` : "-"} |\n`
    }
    s += `\n#### ${L.actDetails}\n\n`
    for (const a of day.activities) s += this.actDetail(a, L)
    if (day.estimatedBudget) s += `**${L.dayBudget}**: ¥${day.estimatedBudget.toFixed(0)}\n\n`
    if (day.notes) s += `> 💡 ${day.notes}\n\n`
    return s
  }

  private static actDetail(a: Activity, L: typeof ZH_LABELS) {
    let s = `##### ${a.time.start} – ${a.time.end} ${a.name}\n\n`
    if (a.description) s += `${a.description}\n\n`
    s += `- 📍 **${L.locLabel}**: ${a.location.name}\n`
    if (a.location.address) s += `- 🏠 **${L.addrLabel}**: ${a.location.address}\n`
    s += `- 🏷️ **${L.typeLabel}**: ${L.actType(a.type)}\n`
    if (a.cost != null) s += `- 💰 **${L.costLabel}**: ¥${a.cost}\n`
    if (a.rating) s += `- ⭐ **${L.ratingLabel}**: ${a.rating.toFixed(1)}/5.0\n`
    if (a.bookingUrl) s += `- 🔗 **${L.bookLabel}**: [link](${a.bookingUrl})\n`
    if (a.notes) s += `- 📝 **${L.notesLabel}**: ${a.notes}\n`
    return s + "\n"
  }

  private static budgetSummary(trip: Trip, L: typeof ZH_LABELS) {
    const total  = trip.itinerary.reduce((s, d) => s + (d.estimatedBudget ?? 0), 0)
    const budgets = trip.itinerary.map((d) => d.estimatedBudget ?? 0)
    let s = `---\n\n## ${L.budgetSummary}\n\n### ${L.overallBudget}\n\n`
    s += `- **${L.totalBudget}**: ¥${total.toFixed(0)}\n`
    s += `- **${L.avgBudget}**: ¥${(total / trip.duration.days).toFixed(0)}\n`
    s += `- **${L.maxDay}**: ¥${Math.max(...budgets).toFixed(0)}\n`
    s += `- **${L.minDay}**: ¥${Math.min(...budgets).toFixed(0)}\n\n`
    s += `### ${L.dailyDetail}\n\n| ${L.dateCol} | ${L.budgetCol} |\n|---|---|\n`
    for (const d of trip.itinerary) {
      const dateStr = d.date.toLocaleDateString(L.dateLocale, { month:"short", day:"numeric" })
      s += `| ${L.tocDayRef(d.dayNumber)} (${dateStr}) | ${d.estimatedBudget ? `¥${d.estimatedBudget.toFixed(0)}` : "-"} |\n`
    }
    return s + "\n"
  }

  private static footer(L: typeof ZH_LABELS) {
    const ts = new Date().toLocaleString(L.dateLocale, { year:"numeric", month:"long", day:"numeric", hour:"2-digit", minute:"2-digit" })
    return `---\n\n*${L.footer} ${ts}*\n\n${L.usage}\n`
  }

  private static downloadFile(content: string, filename: string, mimeType: string) {
    const blob = new Blob([content], { type: mimeType })
    const url  = URL.createObjectURL(blob)
    const a    = document.createElement("a")
    a.href = url; a.download = filename
    document.body.appendChild(a); a.click()
    document.body.removeChild(a); URL.revokeObjectURL(url)
  }
}
