/**
 * PDF export — language-aware, CJK-safe.
 *
 * jsPDF's built-in fonts don't include CJK glyphs, so the old approach
 * produced garbled text for Chinese characters.  Instead we generate a
 * self-contained UTF-8 HTML document that the browser opens in a new tab and
 * auto-triggers a print dialog.  The user saves as PDF from there.  This
 * approach uses the browser's own rendering engine (which handles CJK via
 * system fonts), requires no font embedding, and produces a clean result in
 * both Chinese and English.
 */

import type { Trip, DayPlan, Activity } from "@/types"
import { useUiStore } from "@/stores/uiStore"
import type { Language } from "@/stores/uiStore"

// ── i18n labels used inside the generated HTML ────────────────────────────────

const LABELS: Record<Language, {
  destination: string; dates: string; days: string; activities: string
  status: string; itinerary: string; budgetSummary: string; totalBudget: string
  avgBudget: string; totalAct: string; generatedBy: string; page: string
  budgetLabel: string; notesLabel: string; minLabel: string
  actTypeLabel: (t: string) => string
  statusLabel: (s: string) => string
  dayTitle: (n: number, date: Date) => string
}> = {
  zh: {
    destination: "目的地", dates: "日期", days: "天", activities: "个活动",
    status: "状态", itinerary: "行程详情", budgetSummary: "预算汇总",
    totalBudget: "总预算", avgBudget: "日均预算", totalAct: "活动总数",
    generatedBy: "由 Trip Agent 生成", page: "第", minLabel: "分钟",
    budgetLabel: "当日预算：", notesLabel: "备注：",
    actTypeLabel: (t) => ({ transportation:"交通", attraction:"景点", dining:"餐饮", accommodation:"住宿", shopping:"购物", other:"其他" }[t] ?? t),
    statusLabel: (s) => ({ draft:"草稿", planning:"规划中", confirmed:"已确认", completed:"已完成", cancelled:"已取消" }[s] ?? s),
    dayTitle: (n, d) => `第 ${n} 天 — ${d.toLocaleDateString("zh-CN", { month:"long", day:"numeric", weekday:"short" })}`,
  },
  en: {
    destination: "Destination", dates: "Dates", days: " days", activities: " activities",
    status: "Status", itinerary: "Itinerary Details", budgetSummary: "Budget Summary",
    totalBudget: "Total Budget", avgBudget: "Daily Average", totalAct: "Total Activities",
    generatedBy: "Generated by Trip Agent", page: "Page", minLabel: "min",
    budgetLabel: "Day budget: ", notesLabel: "Notes: ",
    actTypeLabel: (t) => ({ transportation:"Transport", attraction:"Attraction", dining:"Dining", accommodation:"Stay", shopping:"Shopping", other:"Other" }[t] ?? t),
    statusLabel: (s) => ({ draft:"Draft", planning:"Planning", confirmed:"Confirmed", completed:"Completed", cancelled:"Cancelled" }[s] ?? s),
    dayTitle: (n, d) => `Day ${n} — ${d.toLocaleDateString("en-US", { month:"long", day:"numeric", weekday:"short" })}`,
  },
}

const ACT_COLORS: Record<string, string> = {
  transportation: "#3b82f6",
  attraction: "#8b5cf6",
  dining: "#ef4444",
  accommodation: "#10b981",
  shopping: "#f59e0b",
  other: "#6b7280",
}
const ACT_ICONS: Record<string, string> = {
  transportation:"🚗", attraction:"🏛️", dining:"🍽️",
  accommodation:"🏨", shopping:"🛍️", other:"📍",
}

// ── HTML generators ───────────────────────────────────────────────────────────

function activityHtml(act: Activity, L: typeof LABELS["zh"]): string {
  const color = ACT_COLORS[act.type] ?? ACT_COLORS.other
  const icon  = ACT_ICONS[act.type]  ?? ACT_ICONS.other
  const descHtml = act.description ? `<p class="act-desc">${act.description}</p>` : ""
  const costHtml = act.cost != null  ? `<span>💰 ¥${act.cost}</span>` : ""
  return `
    <div class="activity" style="border-left-color:${color}">
      <div class="act-time" style="color:${color}">${act.time.start} – ${act.time.end} (${act.time.duration} ${L.minLabel})</div>
      <div class="act-name">${icon} ${act.name}</div>
      ${descHtml}
      <div class="act-meta">
        <span>📍 ${act.location.name}</span>
        ${costHtml}
        <span class="act-type">${L.actTypeLabel(act.type)}</span>
      </div>
    </div>`
}

function dayHtml(day: DayPlan, L: typeof LABELS["zh"]): string {
  const acts  = day.activities.map((a) => activityHtml(a, L)).join("")
  const budg  = day.estimatedBudget ? `<div class="day-budget">${L.budgetLabel}¥${day.estimatedBudget.toFixed(0)}</div>` : ""
  const notes = day.notes ? `<div class="notes">💡 ${L.notesLabel}${day.notes}</div>` : ""
  return `
    <div class="day">
      <div class="day-header">
        <span class="day-title">${L.dayTitle(day.dayNumber, day.date)}</span>
        <span class="day-count">${day.activities.length} ${L.activities.trim()}</span>
      </div>
      ${acts}${budg}${notes}
    </div>`
}

function buildHtml(trip: Trip, lang: Language): string {
  const L = LABELS[lang]
  const totalBudget = trip.itinerary.reduce((s, d) => s + (d.estimatedBudget ?? 0), 0)
  const totalAct    = trip.itinerary.reduce((s, d) => s + d.activities.length, 0)
  const fmt = (d: Date) =>
    d.toLocaleDateString(lang === "zh" ? "zh-CN" : "en-US", { year:"numeric", month:"long", day:"numeric" })

  return `<!DOCTYPE html>
<html lang="${lang === "zh" ? "zh-CN" : "en"}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>${trip.name}</title>
  <style>
    * { margin:0; padding:0; box-sizing:border-box }
    body {
      font-family: -apple-system, "PingFang SC", "Microsoft YaHei", "Noto Sans CJK SC",
                   BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
      font-size:13px; line-height:1.6; color:#1f2937; background:#fff;
    }
    .page { max-width:800px; margin:0 auto; padding:32px 40px }
    /* Header */
    .trip-header { border-bottom:3px solid #3b82f6; padding-bottom:20px; margin-bottom:28px }
    .trip-name { font-size:26px; font-weight:700; color:#111827; margin-bottom:10px }
    .meta { display:flex; flex-wrap:wrap; gap:14px; font-size:13px; color:#6b7280 }
    .meta-item { display:flex; align-items:center; gap:5px }
    .status-badge { padding:3px 10px; border-radius:12px; font-size:11px; font-weight:600;
                    background:#fef3c7; color:#92400e }
    /* Section */
    .section { margin-top:28px }
    .section-title { font-size:18px; font-weight:600; color:#111827; margin-bottom:16px;
                     padding-bottom:8px; border-bottom:2px solid #e5e7eb }
    /* Day */
    .day { margin-bottom:24px; background:#f9fafb; border-radius:8px; padding:18px }
    .day-header { display:flex; justify-content:space-between; align-items:center;
                  margin-bottom:14px }
    .day-title { font-size:16px; font-weight:600; color:#1f2937 }
    .day-count { font-size:12px; color:#6b7280 }
    .day-budget { margin-top:12px; font-size:13px; font-weight:600; color:#6b7280 }
    /* Activity */
    .activity { background:#fff; border-radius:6px; border-left:4px solid #3b82f6;
                padding:12px 14px; margin-bottom:10px }
    .act-time { font-size:12px; font-weight:600; margin-bottom:4px }
    .act-name { font-size:15px; font-weight:600; color:#111827; margin-bottom:4px }
    .act-desc { font-size:13px; color:#4b5563; margin-bottom:6px }
    .act-meta { display:flex; flex-wrap:wrap; gap:12px; font-size:12px; color:#6b7280 }
    .act-type { background:#e5e7eb; border-radius:4px; padding:1px 6px }
    .notes { margin-top:12px; padding:10px 12px; background:#fffbeb; border-radius:6px;
             font-size:13px; color:#92400e }
    /* Budget cards */
    .budget-grid { display:grid; grid-template-columns:repeat(3,1fr); gap:14px; margin-top:16px }
    .bcard { padding:14px; background:#f3f4f6; border-radius:8px; text-align:center }
    .bcard-label { font-size:12px; color:#6b7280; margin-bottom:4px }
    .bcard-value { font-size:22px; font-weight:700; color:#111827 }
    /* Footer */
    .footer { margin-top:36px; padding-top:16px; border-top:1px solid #e5e7eb;
              text-align:center; font-size:11px; color:#9ca3af }
    @media print {
      body { background:#fff }
      .day { page-break-inside:avoid }
      .activity { page-break-inside:avoid }
    }
  </style>
</head>
<body>
<div class="page">
  <div class="trip-header">
    <div class="trip-name">${trip.name}</div>
    <div class="meta">
      <div class="meta-item">📍 ${trip.destination.name}, ${trip.destination.country}</div>
      <div class="meta-item">📅 ${fmt(trip.duration.startDate)} – ${fmt(trip.duration.endDate)}</div>
      <div class="meta-item">⏱ ${trip.duration.days}${L.days} · ${totalAct}${L.activities}</div>
      <div class="meta-item"><span class="status-badge">${L.statusLabel(trip.status)}</span></div>
    </div>
  </div>

  <div class="section">
    <div class="section-title">${L.itinerary}</div>
    ${trip.itinerary.map((d) => dayHtml(d, L)).join("")}
  </div>

  <div class="section">
    <div class="section-title">${L.budgetSummary}</div>
    <div class="budget-grid">
      <div class="bcard"><div class="bcard-label">${L.totalBudget}</div><div class="bcard-value">¥${totalBudget.toFixed(0)}</div></div>
      <div class="bcard"><div class="bcard-label">${L.avgBudget}</div><div class="bcard-value">¥${trip.duration.days > 0 ? (totalBudget / trip.duration.days).toFixed(0) : 0}</div></div>
      <div class="bcard"><div class="bcard-label">${L.totalAct}</div><div class="bcard-value">${totalAct}</div></div>
    </div>
  </div>

  <div class="footer">${L.generatedBy} · ${new Date().toLocaleString(lang === "zh" ? "zh-CN" : "en-US")}</div>
</div>
<script>window.addEventListener("load",()=>{setTimeout(()=>window.print(),400)})</script>
</body>
</html>`
}

// ── Public API ────────────────────────────────────────────────────────────────

export class PdfExportService {
  static exportToPdf(trip: Trip, lang?: Language): void {
    const l: Language = lang ?? useUiStore.getState().language ?? "zh"
    const html = buildHtml(trip, l)
    const blob = new Blob([html], { type: "text/html;charset=utf-8" })
    const url  = URL.createObjectURL(blob)
    const win  = window.open(url, "_blank")
    if (win) win.addEventListener("afterprint", () => URL.revokeObjectURL(url))
    else URL.revokeObjectURL(url)
  }
}
